version: '3'

services:

  #  start MariaDB, and ensure that data is stored to a mounted volume
  mariadb:
    image: 'mariadb:10'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: root
      MYSQL_PASSWORD: somepassword
    volumes:
      - ./db-data/appdb:/var/lib/mysql
      - ./sql/breeders_mysql.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - adminer-network

  adminer:
      image: adminer
      ports:
        - 8080:8080
      restart: always
      environment:
        ADMINER_DEFAULT_SERVER: mariadb
      depends_on:
        - mariadb
      networks:
        - adminer-network

volumes:
  db-data:

networks:
  adminer-network:


#  postgres:
#    image: 'postgres:14'
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: somepassword
#      POSTGRES_DB: thedb
#    logging:
#      options:
#        max-size: 10m
#        max-file: "3"
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./db-data/the_db:/var/lib/postgresql/data
#      - ./sql/postgres.sql:/docker-entrypoint-initdb.d/create_tables.sql

